// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductosAPI.Data;

#nullable disable

namespace ProductosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129181911_Primer")]
    partial class Primer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductosAPI.Models.CategoriaHabitacion", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCategoria");

                    b.ToTable("CategoriaHabitacion");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Habitación para una persona.",
                            Nombre = "Simple",
                            PrecioBase = 50.00m
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Habitación para dos personas.",
                            Nombre = "Doble",
                            PrecioBase = 80.00m
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Suite de lujo con sala de estar.",
                            Nombre = "Suite",
                            PrecioBase = 150.00m
                        });
                });

            modelBuilder.Entity("ProductosAPI.Models.ConsumoServicio", b =>
                {
                    b.Property<int>("IdConsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConsumo"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaConsumo")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdConsumo");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdServicio");

                    b.ToTable("ConsumoServicio");
                });

            modelBuilder.Entity("ProductosAPI.Models.EstadoReserva", b =>
                {
                    b.Property<int>("IdEstadoReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoReserva"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstadoReserva");

                    b.ToTable("EstadoReserva");

                    b.HasData(
                        new
                        {
                            IdEstadoReserva = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            IdEstadoReserva = 2,
                            Nombre = "Confirmada"
                        },
                        new
                        {
                            IdEstadoReserva = 3,
                            Nombre = "Cancelada"
                        },
                        new
                        {
                            IdEstadoReserva = 4,
                            Nombre = "Completada"
                        });
                });

            modelBuilder.Entity("ProductosAPI.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdReserva");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("ProductosAPI.Models.Habitacion", b =>
                {
                    b.Property<int>("IdHabitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHabitacion"));

                    b.Property<bool>("EstaDisponible")
                        .HasColumnType("bit");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("NumeroHabitacion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("IdHabitacion");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Habitacion");

                    b.HasData(
                        new
                        {
                            IdHabitacion = 1,
                            EstaDisponible = true,
                            IdCategoria = 1,
                            NumeroHabitacion = "101",
                            Piso = 1
                        },
                        new
                        {
                            IdHabitacion = 2,
                            EstaDisponible = true,
                            IdCategoria = 1,
                            NumeroHabitacion = "102",
                            Piso = 1
                        },
                        new
                        {
                            IdHabitacion = 3,
                            EstaDisponible = true,
                            IdCategoria = 2,
                            NumeroHabitacion = "201",
                            Piso = 2
                        },
                        new
                        {
                            IdHabitacion = 4,
                            EstaDisponible = false,
                            IdCategoria = 2,
                            NumeroHabitacion = "202",
                            Piso = 2
                        },
                        new
                        {
                            IdHabitacion = 5,
                            EstaDisponible = true,
                            IdCategoria = 3,
                            NumeroHabitacion = "301",
                            Piso = 3
                        });
                });

            modelBuilder.Entity("ProductosAPI.Models.Huesped", b =>
                {
                    b.Property<int>("IdHuesped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHuesped"));

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdHuesped");

                    b.ToTable("Huesped");
                });

            modelBuilder.Entity("ProductosAPI.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("int");

                    b.Property<int>("IdHabitacion")
                        .HasColumnType("int");

                    b.Property<int>("IdHuesped")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("IdHabitacion");

                    b.HasIndex("IdHuesped");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("ProductosAPI.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            Nombre = "Recepcionista"
                        });
                });

            modelBuilder.Entity("ProductosAPI.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdServicio");

                    b.ToTable("Servicio");

                    b.HasData(
                        new
                        {
                            IdServicio = 1,
                            Nombre = "Servicio a la habitación",
                            Precio = 15.00m
                        },
                        new
                        {
                            IdServicio = 2,
                            Nombre = "Lavandería",
                            Precio = 25.00m
                        },
                        new
                        {
                            IdServicio = 3,
                            Nombre = "Minibar",
                            Precio = 10.00m
                        });
                });

            modelBuilder.Entity("ProductosAPI.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Correo = "admin@example.com",
                            EstaActivo = true,
                            IdRol = 1,
                            PasswordHash = "$2a$11$qMa1JzKkm99KOmBdOv82qO15gSVbiKZlxIgYkqGQ67z0HW4GGncnq"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Correo = "recepcionista@example.com",
                            EstaActivo = true,
                            IdRol = 2,
                            PasswordHash = "$2a$11$azWOhJcRYYhNDBB2xCVFhe0Wuya3kemkgm02BHusCRv3vjFzhkRRW"
                        });
                });

            modelBuilder.Entity("ProductosAPI.Models.ConsumoServicio", b =>
                {
                    b.HasOne("ProductosAPI.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductosAPI.Models.Servicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("ProductosAPI.Models.Factura", b =>
                {
                    b.HasOne("ProductosAPI.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ProductosAPI.Models.Habitacion", b =>
                {
                    b.HasOne("ProductosAPI.Models.CategoriaHabitacion", "CategoriaHabitacion")
                        .WithMany("Habitaciones")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaHabitacion");
                });

            modelBuilder.Entity("ProductosAPI.Models.Reserva", b =>
                {
                    b.HasOne("ProductosAPI.Models.EstadoReserva", "EstadoReserva")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEstadoReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductosAPI.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("IdHabitacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductosAPI.Models.Huesped", "Huesped")
                        .WithMany("Reservas")
                        .HasForeignKey("IdHuesped")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductosAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoReserva");

                    b.Navigation("Habitacion");

                    b.Navigation("Huesped");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProductosAPI.Models.Usuario", b =>
                {
                    b.HasOne("ProductosAPI.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("ProductosAPI.Models.CategoriaHabitacion", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("ProductosAPI.Models.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProductosAPI.Models.Huesped", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ProductosAPI.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
